### ISSUE TITLE
Metafields not available in the Order Status Page in the Checkout Editor (only)

### ISSUE THREAD

**Issue by lucasprag** [Shopify/ui-extensions#1532]
## Please list the package(s) involved in the issue, and include the version you are using

```
    "@shopify/app": "3.50.2",
    "@shopify/checkout-ui-extensions-react": "0.27.3",
    "@shopify/cli": "3.50.2",
```

## Describe the bug

The app metafields should be available in the Shopify Checkout Editor for the Order Status Page but they are not.

## Steps to reproduce the behavior:

1. Create a simple `checkout_ui_extension` extension using the `useAppMetafields()` hook like the example below.
```toml
# extensions/order-status-extension/shopify.ui.extension.toml
type = "checkout_ui_extension"
name = "OSP Example"

extension_points = [
  'Checkout::ThankYou::Dynamic::Render',
  'Checkout::OrderStatus::Dynamic::Render',
]

[[metafields]]
namespace = "example"
key = "example_key"

[capabilities]
network_access = true
```

```tsx
# extensions/order-status-extension/src/index.tsx
import {
  Text,
  render,
  useAppMetafields,
} from '@shopify/checkout-ui-extensions-react';

const App = () => {
  const metafields = useAppMetafields();
  console.log('metafields', metafields);
  return <Text>Hello 👋🏼</Text>;
};

render('Checkout::ThankYou::Dynamic::Render', () => <App />);
render('Checkout::OrderStatus::Dynamic::Render', () => <App />);
```
2. create a metafield in your store using the Shopify API
2. add the extension to your thank you page and your order status page
3. go thought checkout and in the console that the metafields show up in the console for both pages
4. go to the Shopify Checkout Editor, see the metafields show up in the thank you page, but not in the order status page 🐞 

## Expected behavior

The app metafields should be available in the Shopify Checkout Editor for the Order Status Page -- as they are for the Thank you page and during checkout fopr both pages -- but they are not available.

#### During checkout, working as expected:

<img width="1901" alt="thank you page" src="https://github.com/Shopify/ui-extensions/assets/2293178/8a64c751-cab2-4e69-bbaf-991b587bd5d3">

#### In the checkout editor, working as expected:

<img width="2537" alt="thank you page in the editor" src="https://github.com/Shopify/ui-extensions/assets/2293178/5cea065b-33fa-4c1f-9715-c4aed3f7d125">

#### During checkout, working as expected:

<img width="2077" alt="order status page" src="https://github.com/Shopify/ui-extensions/assets/2293178/0bd60add-24f5-4284-8cea-2dc8e1159ef7">

#### In the checkout editor, metafields should be available but they are not 💥 :

<img width="2542" alt="order status page in the checkout editor" src="https://github.com/Shopify/ui-extensions/assets/2293178/5b2ee82f-13ba-47c2-a2b0-31be09cf9802">
