### ISSUE TITLE
[Customer Accounts UI] Checkout settings incorrectly return camelCase keys instead of original format

### ISSUE THREAD

**Issue by gil--** [Shopify/ui-extensions#1812]
## Please list the package(s) involved in the issue, and include the version you are using

"@shopify/ui-extensions": "^2024.1.1",
"@shopify/ui-extensions-react": "^2024.1.1",

## Describe the bug

This took a while to narrow down but for some strange reason, the order status page is incorrectly parsing checkout setting keys into camelCase. The checkout editor does not do this for the order status, only the actual customer accounts order status page.

### Expected:
![CleanShot 2024-03-06 at 20 49 20@2x](https://github.com/Shopify/ui-extensions/assets/3484527/24605332-8eb4-4fcd-b2f5-45e207ef7654)

### Actual:
![CleanShot 2024-03-06 at 20 49 31@2x](https://github.com/Shopify/ui-extensions/assets/3484527/38624d1b-67cd-40f6-a1b3-df7f305c90d2)

## Steps to reproduce the behavior:

Add a checkout extension setting with an underscore such as:

```toml
[extensions.settings]
  [[extensions.settings.fields]]
  key = "block_location"
  type = "single_line_text_field"
  name = "App Block ID"

```

Load settings in customer accounts order status and notice it transforms the key into camel case. This is breaking a lot of functionality in my app that uses underscore keys and expects that format everywhere else.

## Expected behavior

Checkout setting keys use the original format.

## Screenshots

See above
