### ISSUE TITLE
[Checkout Editor] Default values

### ISSUE THREAD

**Issue by gil--** [Shopify/ui-extensions#739]
## Please list the related package(s)

checkout-ui-extensions

## If this related to specific APIs or components, please list them here

For example:

```toml
[settings]
  [[settings.fields]]
  key = "title"
  type = "single_line_text_field"
  name = "Title (optional)"
  description = "Enter a title for the block."
  ```
  
Would have a default:

```toml
[settings]
  [[settings.fields]]
  key = "title"
  type = "single_line_text_field"
  name = "Title (optional)"
  description = "Enter a title for the block."
  default = "Hello!!"
  ```
```

## Is your feature request related to a problem? Please describe.

Would be nice to specify a default value for a toml input setting similar to the [default](https://shopify.dev/docs/themes/architecture/settings/input-settings#standard-attributes) attribute for theme settings.

## Describe the changes you are looking for

Add ability to specify the default value for a setting via new `default` attribute on all input setitngs.

## Describe alternatives you’ve considered

I specify a default in the extension code but it's not ideal as there's nothing selected within the checkout editor. Does not work super well if you want a checkbox selected by default for example.
